name: 'First responder'
description: 'Catch team pings from issues and pull requests outside of your repository'
inputs:
  token:
    description: 'An access token.'
    required: true
  team:  # id of input
    description: 'The team ping to search for that is part of the `org` specified below. Do not include the org name (for example, use `docs-content-ecosystem`). Issues and pull requests authored or commented on by members of `team` are ignored unless you specify an alternate `ignore-team` parameter.' 
    required: true
  org: 
    description: 'The organization where the action should search for issues and pull requests.'
    required: true
  since:
    description: 'The start date to search for team pings. The action searches for issues or pull requests created since the date specified. Form: {4 digit year}-{month}-{day}. For example: "2020-5-20"'
    required: false
    default: '2020-1-1'
  project-board: 
    description: 'The URL of the project board to place issues and pull requests. Must be an org project board.'
    required: true
  project-column:
    description: 'The id of the column to add issues and pull requests.'
    required: true
  ignore-team:
    description: 'Ignores issues and pull requests authored or commented on by members of this team. Issues and pull requests authored or commented on by members of `team` are ignored unless you specify an alternate `ignore-team` parameter. You can use `ignore-team` to specify a larger team or a team that does not match the team ping being searched. The value you specify for `ignore-team` overrides the `team` value.'
    required: false
  ignore-repos: 
    description: 'Repositories to ignore when searching issues and pull requests. You can add more than one repository by using a comma-separated list. Format: {owner}/{repo}. For example: octocat/hello-world'
    required: false
  ignore-authors:
    description: 'Ignores issues and pull requests authored by these accounts. You can add more than one repository by using a comma-separated list (for example, "actions-bot, hubot")'
    required: false
  ignore-commenters:
    description: 'Ignores issues and pull requests commented by thee accounts. You can add more than one repository by using a comma-separated list (for example, "actions-bot, hubot")'
    required: false
  ignore-labels:
    description: 'Ignores issues and pull requests with specific labels. You can add more than one label by using a comma-separated list (for example, "space-2x, autogen")'
    required: false
  include-review-requests:
    description: 'If you want to include any requests for review for the team.'
    required: false
  comment-body: 
    description: 'A comment added to the issue or pull request.'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
